#!/usr/bin/env bash

set -e

cd $(dirname $0)/..

echo -----------------------------------------------------------------------
echo "[Govendor] start..."
start_tm=`date +%s%N`

govendor sync
#govendor fetch code.yourdomain.com/{{username}}/{{project}}

echo ""
govendor list
echo ""

end_tm=`date +%s%N`
use_tm=`echo $end_tm $start_tm | awk '{ print ($1 - $2) / 1000000000}'`

echo "[Govendor] finished in ${use_tm}s"